service: si-sewls-auto-query-daily
#plugins:
#  - serverless-offline
provider:
  memorySize: 128
  name: aws
  endpointType: regional
  region: cn-northwest-1 
  stackName: auto-query-daily-lambda-${opt:stage}
  runtime: nodejs12.x
  versionFunctions: true
  deploymentBucket: 
    name: si-sewls-auto-query-daily-lambda-deploy-${opt:stage}
functions:
  query-anthena:
    handler: SewlsAutoQueryDaily.autoQueryHandlerDaily
    name: si-sewls-auto-query-daily-${opt:stage}
    timeout: 60 # Timeout for this specific function.
    environment:
      region: cn-northwest-1
      outputLocation: s3://si-sewls-query-${opt:stage}/query-daily/
      queryDaysBefore: 2
      guleCrawelTableName: si_sewls_save_data
    events:
      - eventBridge:
        # using the default AWS event bus
        schedule: cron(30 1 * * ? *)
