service: si-sewls-save-data
plugins:
  - serverless-offline
provider:
  memorySize: 128
  name: aws
  endpointType: regional
  region: cn-northwest-1
  stackName: si-sewls-save-data-lambda-${opt:stage}
  runtime: nodejs12.x
  versionFunctions: true
  deploymentBucket: 
    name: si-sewls-save-data-lambda-deploy-${opt:stage}
functions:
  save-data:
    handler: ./dist/save/SewlsSaveData.saveStatisticDataHandler
    name: si-sewls-save-data-lambda-${opt:stage}
    environment:
      region: cn-northwest-1
      npm_package_version: 1.0.0
      DELIVERY_STREAM_NAME: si-sewls-save-data-firehose-${opt:stage}
    events:
      - http:
          path: /si-sewls-api/v1/whitelabel/statistic
          method: post